export interface CatalogProduct {
  id: string;
  name: string;
  category: string;
  price: number;
  commissionRate: number;
  monthlySales: number;
  stockStatus: '现货' | '预售' | '少量库存';
  heroTone: string;
  tags: string[];
  targetAudience: string;
  sellingPoints: string[];
  specs: Array<{ label: string; value: string }>;
  recommendationAngles: string[];
  complianceNotes: string[];
}

export interface MerchantProfile {
  id: string;
  name: string;
  entry: string;
  city: string;
  district: string;
  address: string;
  licenseNo: string;
  qualification: '旗舰资质' | '品牌自营' | '工坊认证' | '严选合作';
  score: number;
  foundedYear: number;
  responseTime: string;
  fulfillmentRate: number;
  repeatRate: number;
  productCount: number;
  monthlySales: number;
  averageCommissionRate: number;
  certifications: string[];
  merchantTags: string[];
  summary: string;
  strengths: string[];
  riskNotes: string[];
  servicePolicies: string[];
  audience: string[];
  products: CatalogProduct[];
}

export const CONTENT_ENTRIES = [
  '全部入口',
  '光选定制',
  '东方美学',
  '有机素食',
  '宠物星球',
  '光选非遗',
  '匠心手作',
  '静读间',
  '设计师品牌',
];

export const MERCHANT_CATALOG: MerchantProfile[] = [
  {
    id: 'merchant-gx-001',
    name: '青禾光选定制生活馆',
    entry: '光选定制',
    city: '杭州',
    district: '滨江区',
    address: '浙江省杭州市滨江区江南大道 588 号创意园 B 座 6F',
    licenseNo: '91330108MA2GX2026Q',
    qualification: '旗舰资质',
    score: 4.8,
    foundedYear: 2018,
    responseTime: '12 分钟',
    fulfillmentRate: 98,
    repeatRate: 37,
    productCount: 126,
    monthlySales: 28640,
    averageCommissionRate: 14,
    certifications: ['商户个人信息已提交', '商户身份证已上传', '商户营业执照已上传', '注册信息已填写'],
    merchantTags: ['节日礼赠', '企业团购', '高复购'],
    summary: '主打节日礼盒、企业伴手礼和家庭生活套装，供应链稳定，适合做礼赠场景、办公室福利和家庭品质生活推荐。',
    strengths: ['礼盒包装完成度高，开箱内容适合短视频展示', '支持少量定制卡片，企业采购转化稳定', '售后响应快，破损补发规则清晰'],
    riskNotes: ['定制款需提前确认交付日期', '企业大单价格随包装方案浮动'],
    servicePolicies: ['7 天无理由适用未拆封商品', '破损签收 24 小时内补发', '企业订单可开具专票'],
    audience: ['企业行政与 HR', '节日礼赠人群', '注重生活质感的家庭用户'],
    products: [
      {
        id: 'SPU-GX-001',
        name: '青禾节日茶器香氛礼盒',
        category: '节日礼盒',
        price: 299,
        commissionRate: 16,
        monthlySales: 4820,
        stockStatus: '现货',
        heroTone: '#e0f2fe',
        tags: ['高客单', '礼赠', '可定制'],
        targetAudience: '25-45 岁礼赠与企业福利用户',
        sellingPoints: ['茶器、香氛、贺卡一盒完整解决送礼', '外包装质感稳定，适合开箱展示', '支持企业定制祝福卡'],
        specs: [
          { label: '套装内容', value: '陶瓷茶杯 2 只、木质托盘、香氛蜡烛、定制卡片' },
          { label: '发货时效', value: '普通款 48 小时内发货，定制款 5-7 天' },
          { label: '包装尺寸', value: '32cm x 24cm x 9cm' },
        ],
        recommendationAngles: ['节前送礼不用纠结', '办公室体面伴手礼', '适合镜头展示的开箱礼盒'],
        complianceNotes: ['香氛成分备案齐全', '定制文案需避免功效承诺'],
      },
      {
        id: 'SPU-GX-002',
        name: '家庭清洁香氛补充套装',
        category: '生活套装',
        price: 129,
        commissionRate: 12,
        monthlySales: 9360,
        stockStatus: '现货',
        heroTone: '#dcfce7',
        tags: ['家庭刚需', '复购', '轻决策'],
        targetAudience: '新家入住、租房和家庭日常清洁人群',
        sellingPoints: ['清洁、除味、香氛三个需求一次覆盖', '客单价友好，适合直播间连带推荐', '补充装复购周期清晰'],
        specs: [
          { label: '套装内容', value: '多功能清洁剂 2 瓶、香氛喷雾 1 瓶、补充装 1 袋' },
          { label: '适用场景', value: '厨房、卫生间、玄关、衣柜' },
          { label: '保质期', value: '24 个月' },
        ],
        recommendationAngles: ['新家入住第一套清洁香氛', '让家里闻起来更干净', '低门槛复购款'],
        complianceNotes: ['不可宣称杀菌消毒功效', '需提示远离儿童存放'],
      },
      {
        id: 'SPU-GX-003',
        name: '企业福利轻食礼袋',
        category: '企业福利',
        price: 89,
        commissionRate: 10,
        monthlySales: 6280,
        stockStatus: '少量库存',
        heroTone: '#fef3c7',
        tags: ['团购', '轻食', '高性价比'],
        targetAudience: '中小企业行政采购、团队活动采购',
        sellingPoints: ['坚果、燕麦、果干组合适合办公室分享', '单价可控，适合批量采购', '可做部门活动小礼品'],
        specs: [
          { label: '净含量', value: '约 760g' },
          { label: '起订量', value: '20 袋起支持团购价' },
          { label: '储存方式', value: '阴凉干燥处保存' },
        ],
        recommendationAngles: ['团队下午茶不踩雷', '预算友好的员工福利', '办公室常备轻食'],
        complianceNotes: ['坚果过敏人群需谨慎', '食品详情页需展示配料表'],
      },
    ],
  },
  {
    id: 'merchant-df-002',
    name: '云岚东方美学器物店',
    entry: '东方美学',
    city: '苏州',
    district: '姑苏区',
    address: '江苏省苏州市姑苏区平江路 218 号',
    licenseNo: '91320508MA2DF2026L',
    qualification: '品牌自营',
    score: 4.7,
    foundedYear: 2016,
    responseTime: '18 分钟',
    fulfillmentRate: 96,
    repeatRate: 31,
    productCount: 84,
    monthlySales: 17420,
    averageCommissionRate: 13,
    certifications: ['商户个人信息已提交', '商户身份证已上传', '商户营业执照已上传', '注册信息已填写'],
    merchantTags: ['新中式', '家居摆件', '拍摄友好'],
    summary: '以新中式家居器物为主，产品审美统一，适合茶室、书房、家居改造和节气生活方式内容。',
    strengths: ['视觉风格稳定，适合图文和短视频陈列', '客单覆盖入门到进阶，方便分层推荐', '原创款有稳定故事线'],
    riskNotes: ['陶瓷类运输需提醒验货', '手工釉色存在自然差异'],
    servicePolicies: ['破损包赔', '支持礼盒包装', '非质量问题定制款不退换'],
    audience: ['新中式家居用户', '茶饮与香道爱好者', '送礼人群'],
    products: [
      {
        id: 'SPU-DF-101',
        name: '宋风陶瓷香插与花器套装',
        category: '家居器物',
        price: 238,
        commissionRate: 15,
        monthlySales: 3620,
        stockStatus: '现货',
        heroTone: '#f5e8d3',
        tags: ['新中式', '桌面美学', '礼盒'],
        targetAudience: '喜欢茶室、书房和新中式软装的用户',
        sellingPoints: ['香插与花器可分开使用，一套覆盖多个桌面场景', '釉色温润，上镜效果稳定', '礼盒包装适合乔迁礼'],
        specs: [
          { label: '材质', value: '高温陶瓷、胡桃木底座' },
          { label: '工艺', value: '手工修胚，高温釉烧' },
          { label: '适用', value: '线香、干花、茶席陈列' },
        ],
        recommendationAngles: ['低成本搭出书房氛围', '茶席角落的点睛器物', '乔迁礼不落俗'],
        complianceNotes: ['手工釉色差异需在内容中说明', '易碎品需提醒签收验货'],
      },
      {
        id: 'SPU-DF-102',
        name: '东方纹样桑蚕丝丝巾',
        category: '配饰礼赠',
        price: 189,
        commissionRate: 12,
        monthlySales: 5180,
        stockStatus: '现货',
        heroTone: '#fee2e2',
        tags: ['送礼', '东方纹样', '轻奢'],
        targetAudience: '通勤女性、母亲节礼赠和配饰用户',
        sellingPoints: ['图案有东方纹样故事，内容可讲性强', '价格适中，适合礼赠', '搭配方式多，适合短视频示范'],
        specs: [
          { label: '材质', value: '桑蚕丝混纺' },
          { label: '尺寸', value: '90cm x 90cm' },
          { label: '护理', value: '建议冷水手洗或专业干洗' },
        ],
        recommendationAngles: ['一条丝巾提升基础穿搭', '送妈妈不容易出错', '东方纹样的日常化搭配'],
        complianceNotes: ['材质比例按详情页标注', '避免绝对化品质描述'],
      },
    ],
  },
  {
    id: 'merchant-ys-003',
    name: '素间有机轻食研究所',
    entry: '有机素食',
    city: '上海',
    district: '徐汇区',
    address: '上海市徐汇区龙华中路 596 号绿地中心 12F',
    licenseNo: '91310104MA2YS2026S',
    qualification: '严选合作',
    score: 4.9,
    foundedYear: 2020,
    responseTime: '9 分钟',
    fulfillmentRate: 97,
    repeatRate: 42,
    productCount: 92,
    monthlySales: 32410,
    averageCommissionRate: 11,
    certifications: ['商户个人信息已提交', '商户身份证已上传', '商户营业执照已上传', '注册信息已填写'],
    merchantTags: ['轻食', '控糖', '高复购'],
    summary: '专注植物蛋白、谷物轻食和冷压果汁，适合健康饮食、办公室轻食、体重管理和素食生活方式内容。',
    strengths: ['复购周期短，组合装转化稳定', '配料表清晰，适合做成分讲解', '覆盖早餐、下午茶、代餐多个时段'],
    riskNotes: ['食品内容需避免医疗或减肥承诺', '冷链商品需关注配送城市'],
    servicePolicies: ['冷链破损可补发', '临期批次不参与推广', '支持组合装试吃反馈'],
    audience: ['健康饮食用户', '办公室白领', '素食与控糖人群'],
    products: [
      {
        id: 'SPU-YS-201',
        name: '植物蛋白早餐杯 7 日装',
        category: '轻食早餐',
        price: 119,
        commissionRate: 12,
        monthlySales: 11840,
        stockStatus: '现货',
        heroTone: '#dcfce7',
        tags: ['高复购', '早餐', '植物蛋白'],
        targetAudience: '早八通勤、健身和控糖饮食用户',
        sellingPoints: ['7 天装降低选择成本', '开袋即食，适合办公室', '植物蛋白和谷物搭配，饱腹感明确'],
        specs: [
          { label: '容量', value: '7 杯/盒' },
          { label: '容量规格', value: '每杯 55g' },
          { label: '尺寸', value: '单杯约 8cm x 8cm x 7cm' },
          { label: '主要配料', value: '燕麦、豌豆蛋白、奇亚籽、冻干水果' },
          { label: '营养价值', value: '植物蛋白、膳食纤维和谷物能量补充' },
          { label: '烹饪方式', value: '加入牛奶、豆奶或酸奶后静置食用' },
          { label: '食用方式', value: '加入牛奶、豆奶或酸奶静置 3 分钟' },
          { label: '送货与退货', value: '常温配送；未拆封 7 天内可申请退货' },
        ],
        recommendationAngles: ['不用早起也能吃好早餐', '办公室抽屉里的健康储备', '一周早餐不重样'],
        complianceNotes: ['不可宣称治疗或减肥效果', '过敏原需提示谷物和坚果可能交叉'],
      },
      {
        id: 'SPU-YS-202',
        name: '冷压果蔬汁周计划',
        category: '冷链饮品',
        price: 168,
        commissionRate: 10,
        monthlySales: 6940,
        stockStatus: '预售',
        heroTone: '#bbf7d0',
        tags: ['冷链', '果蔬', '周计划'],
        targetAudience: '关注饮食结构、蔬果摄入不足的用户',
        sellingPoints: ['按周组合，口味不重复', '冷压工艺保留新鲜口感', '适合健康生活方式内容'],
        specs: [
          { label: '容量', value: '6 瓶/组' },
          { label: '容量规格', value: '每瓶 300ml' },
          { label: '尺寸', value: '单瓶约 6cm x 6cm x 16cm' },
          { label: '营养价值', value: '补充蔬果摄入，含天然果蔬风味' },
          { label: '烹饪方式', value: '冷藏后直接饮用，开瓶后尽快饮用' },
          { label: '配送', value: '冷链城市次日达，部分城市隔日达' },
          { label: '送货与退货', value: '冷链配送；生鲜类非质量问题不支持退货' },
          { label: '保质期', value: '冷藏 7 天' },
        ],
        recommendationAngles: ['把喝饮料换成喝果蔬', '周末补充冰箱计划', '健康饮食打卡搭子'],
        complianceNotes: ['不可替代正餐或医疗建议', '需标注冷藏保存'],
      },
    ],
  },
  {
    id: 'merchant-pet-004',
    name: '栖木宠物星球旗舰店',
    entry: '宠物星球',
    city: '成都',
    district: '锦江区',
    address: '四川省成都市锦江区东大街 99 号宠物产业园 3F',
    licenseNo: '91510104MA2PET2026P',
    qualification: '旗舰资质',
    score: 4.8,
    foundedYear: 2017,
    responseTime: '15 分钟',
    fulfillmentRate: 99,
    repeatRate: 45,
    productCount: 138,
    monthlySales: 41260,
    averageCommissionRate: 13,
    certifications: ['商户个人信息已提交', '商户身份证已上传', '商户营业执照已上传', '注册信息已填写'],
    merchantTags: ['猫狗通用', '高复购', '测评素材充足'],
    summary: '覆盖宠物主粮、冻干零食和智能用品，用户复购强，适合宠物测评、养宠新手指南和囤货清单。',
    strengths: ['宠物内容天然有互动性，适合真实使用展示', '冻干零食复购强，转化链路短', '客服对适口性问题响应快'],
    riskNotes: ['宠物食品需避免医疗功效宣称', '不同宠物适口性有个体差异'],
    servicePolicies: ['未开封 7 天可退', '适口性问题提供客服建议', '破损漏气补发'],
    audience: ['新手养宠人群', '多猫多狗家庭', '关注配料的宠物主人'],
    products: [
      {
        id: 'SPU-PET-301',
        name: '鸡肉冻干训练奖励桶',
        category: '宠物零食',
        price: 79,
        commissionRate: 14,
        monthlySales: 15620,
        stockStatus: '现货',
        heroTone: '#ede9fe',
        tags: ['冻干', '训练奖励', '复购'],
        targetAudience: '猫狗家庭、新手训练和互动内容用户',
        sellingPoints: ['单颗小粒，适合训练奖励', '配料简单，内容讲解门槛低', '桶装方便保存和展示'],
        specs: [
          { label: '净含量', value: '220g' },
          { label: '适用对象', value: '3 月龄以上猫犬' },
          { label: '储存方式', value: '密封避光，开封后 30 天内食用' },
        ],
        recommendationAngles: ['训练握手和召回的小奖励', '新手养宠零食第一桶', '多宠家庭囤货装'],
        complianceNotes: ['不能替代主粮', '需按体重控制喂食量'],
      },
      {
        id: 'SPU-PET-302',
        name: '低尘豆腐猫砂 6 包组',
        category: '宠物清洁',
        price: 159,
        commissionRate: 11,
        monthlySales: 18340,
        stockStatus: '现货',
        heroTone: '#fef9c3',
        tags: ['刚需', '囤货', '猫砂'],
        targetAudience: '猫家庭、租房养猫和多猫家庭',
        sellingPoints: ['消耗品属性强，复购明确', '6 包组适合囤货', '低尘和结团表现适合实测内容'],
        specs: [
          { label: '规格', value: '2.5kg x 6 包' },
          { label: '香型', value: '原味/绿茶可选' },
          { label: '适用', value: '单猫约 6-8 周用量' },
        ],
        recommendationAngles: ['多猫家庭省心囤货', '租房养猫除味方案', '猫砂真实结团测试'],
        complianceNotes: ['不同猫咪接受度不同', '不可直接大量倒入马桶'],
      },
    ],
  },
  {
    id: 'merchant-fy-005',
    name: '澄光非遗手作工坊',
    entry: '光选非遗',
    city: '厦门',
    district: '思明区',
    address: '福建省厦门市思明区沙坡尾艺术西区 42 号',
    licenseNo: '91350203MA2FY2026H',
    qualification: '工坊认证',
    score: 4.6,
    foundedYear: 2014,
    responseTime: '24 分钟',
    fulfillmentRate: 94,
    repeatRate: 28,
    productCount: 57,
    monthlySales: 9820,
    averageCommissionRate: 18,
    certifications: ['商户个人信息已提交', '商户身份证已上传', '商户营业执照已上传', '注册信息已填写'],
    merchantTags: ['文化礼赠', '手工制作', '高佣金'],
    summary: '以香囊、蓝染、竹编等手作商品为主，故事性强，适合文化内容、节气礼赠和亲子手作场景。',
    strengths: ['每款商品都有工艺故事，内容素材丰富', '佣金率较高，适合深度种草', '小批量独特性强'],
    riskNotes: ['手作产能有限，大促前需确认库存', '手工纹理差异需提前说明'],
    servicePolicies: ['非质量问题定制款不退', '破损补发', '支持工艺说明素材包'],
    audience: ['文化礼赠用户', '亲子手作用户', '喜欢小众原创的人群'],
    products: [
      {
        id: 'SPU-FY-401',
        name: '节气草本香囊礼盒',
        category: '非遗礼赠',
        price: 96,
        commissionRate: 20,
        monthlySales: 4210,
        stockStatus: '少量库存',
        heroTone: '#ffe4e6',
        tags: ['节气', '手作', '高佣金'],
        targetAudience: '节气礼赠、亲子手作和传统文化用户',
        sellingPoints: ['草本香气和节气主题结合，故事完整', '小礼盒客单友好', '适合端午、七夕、中秋等节点'],
        specs: [
          { label: '内容', value: '香囊 2 枚、草本替换包 2 袋、工艺卡' },
          { label: '工艺', value: '手工缝制，传统纹样刺绣' },
          { label: '香型', value: '艾草、薄荷、桂花三款可选' },
        ],
        recommendationAngles: ['把节气仪式感带回家', '送小朋友的传统文化礼物', '小预算文化礼赠'],
        complianceNotes: ['香囊不作驱虫医疗功效宣称', '孕妇和婴幼儿使用需谨慎提示'],
      },
      {
        id: 'SPU-FY-402',
        name: '蓝染棉麻托特包',
        category: '手作配饰',
        price: 168,
        commissionRate: 17,
        monthlySales: 2380,
        stockStatus: '预售',
        heroTone: '#dbeafe',
        tags: ['蓝染', '小众包袋', '手作'],
        targetAudience: '喜欢自然风穿搭和小众手作包的人群',
        sellingPoints: ['每只纹理不同，独特性强', '容量适合通勤和周末出行', '蓝染工艺适合拍过程故事'],
        specs: [
          { label: '材质', value: '棉麻混纺，植物蓝染' },
          { label: '尺寸', value: '38cm x 34cm，肩带 28cm' },
          { label: '维护', value: '初次洗涤可能轻微浮色，建议单独手洗' },
        ],
        recommendationAngles: ['不会撞包的通勤托特', '蓝染纹理怎么形成', '自然风穿搭点睛'],
        complianceNotes: ['需说明纹理随机', '深色衣物初期避免摩擦浅色面料'],
      },
    ],
  },
  {
    id: 'merchant-sg-006',
    name: '知物静读间书房用品',
    entry: '静读间',
    city: '北京',
    district: '朝阳区',
    address: '北京市朝阳区酒仙桥路 4 号 798 艺术区 D12',
    licenseNo: '91110105MA2READ26J',
    qualification: '严选合作',
    score: 4.7,
    foundedYear: 2019,
    responseTime: '16 分钟',
    fulfillmentRate: 97,
    repeatRate: 33,
    productCount: 73,
    monthlySales: 14350,
    averageCommissionRate: 12,
    certifications: ['商户个人信息已提交', '商户身份证已上传', '商户营业执照已上传', '注册信息已填写'],
    merchantTags: ['书房', '纸品', '效率工具'],
    summary: '围绕阅读灯、纸品、书签和桌面收纳，适合阅读习惯、学习效率、书房改造和礼赠内容。',
    strengths: ['场景明确，容易做前后对比', '产品客单跨度健康', '用户评论集中在质感和实用性'],
    riskNotes: ['电子类产品需要说明质保', '书单类产品受库存批次影响'],
    servicePolicies: ['阅读灯 1 年质保', '纸品未拆封 7 天可退', '套装缺件补发'],
    audience: ['学生与备考人群', '阅读爱好者', '桌面整理用户'],
    products: [
      {
        id: 'SPU-SG-501',
        name: '护眼阅读灯 Pro',
        category: '书房设备',
        price: 269,
        commissionRate: 12,
        monthlySales: 5260,
        stockStatus: '现货',
        heroTone: '#e0e7ff',
        tags: ['阅读灯', '桌面', '质保'],
        targetAudience: '学生、阅读爱好者和夜间办公人群',
        sellingPoints: ['灯臂角度大，适合桌面改造展示', '三档色温覆盖阅读和办公', '质保明确，决策负担低'],
        specs: [
          { label: '色温', value: '3000K/4000K/5000K 三档' },
          { label: '功率', value: '12W LED' },
          { label: '质保', value: '整机 1 年' },
        ],
        recommendationAngles: ['夜读桌面的第一盏灯', '备考桌面改造', '小书房不刺眼照明'],
        complianceNotes: ['护眼描述需基于检测报告', '不可宣称治疗近视'],
      },
      {
        id: 'SPU-SG-502',
        name: '年度阅读手账套装',
        category: '纸品文具',
        price: 98,
        commissionRate: 13,
        monthlySales: 7340,
        stockStatus: '现货',
        heroTone: '#f3f4f6',
        tags: ['手账', '阅读记录', '礼赠'],
        targetAudience: '读书博主、学生和纸品爱好者',
        sellingPoints: ['阅读记录模板完整，适合打卡内容', '配套书签和贴纸提升开箱感', '价格适合自用和送礼'],
        specs: [
          { label: '套装', value: '手账本、索引贴、书签 4 枚、贴纸 2 张' },
          { label: '内页', value: '120g 道林纸，192 页' },
          { label: '尺寸', value: 'A5' },
        ],
        recommendationAngles: ['读完一本书留下痕迹', '新年阅读计划工具', '纸品控开箱'],
        complianceNotes: ['纸张克重按批次标注', '注意展示实际内页'],
      },
    ],
  },
];

export const getAllProducts = () => MERCHANT_CATALOG.flatMap(merchant => merchant.products);

export const formatCatalogNumber = (value: number) => value.toLocaleString('zh-CN');

export const formatCatalogCurrency = (value: number) => `¥${value.toLocaleString('zh-CN')}`;
